### ISSUE TITLE
Regarding the URL used in the script

### ISSUE THREAD

**Issue by CaptainDaVinci** [ju57u5/YoutubeScript#1]
Could you explain how you came across the URLs used for searching, converting and downloading, I've been trying to do the same thing but with no success.

- Why does the URL used while converting make use of `cs` and `time` ? 
- What is the reason for opening the `convertFrame` URL ? (I understand that without this the conversion wont take place, but I want to better understand it's working.

**Comment by ju57u5** [comment]
I just recreated the process my browser did by analyzing it with the developer tools. The site changed this process and I haven't looked at this a long time, so I'm not sure.
ConvertFrame was probably to start the conversion on a specific server (they very likely have more than one).
Time and cs no idea.

**Comment by CaptainDaVinci** [comment]
Your code still works :+1: , and helped me make my code work. Thanks!
